### ISSUE TITLE
Devos without scripture

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/newspring-app#184]
There exists at least one devo without scripture. Resulting in this:

![img_7131](https://cloud.githubusercontent.com/assets/816517/13887630/3031cf00-ed13-11e5-9df0-9d539fae6ef5.PNG)

![img_7132](https://cloud.githubusercontent.com/assets/816517/13887632/3487e8b4-ed13-11e5-9503-778811824e0a.PNG)

We need a solution for this type of scenario. Thoughts:

1) require scripture (not flexible)
2) disable scripture link when no scripture
3) don't show the toggle when no scripture (i like this, but may take some reworking of our component)

**Comment by samclaridge** [comment]
I’d be in favor of option 3, it’s the one that makes the most sense in relation to the existing patterns within the app.

Samuel Claridge

— Sent from
https://polymail.io/

On Fri, Mar 18, 2016 at 2:12 PM John Pinkerton

<
mailto:John Pinkerton <notifications@github.com>
> wrote:

There exists at least one devo without scripture. Resulting in this:

https://cloud.githubusercontent.com/assets/816517/13887630/3031cf00-ed13-11e5-9df0-9d539fae6ef5.PNG
https://cloud.githubusercontent.com/assets/816517/13887632/3487e8b4-ed13-11e5-9503-778811824e0a.PNG

We need a solution for this type of scenario. Thoughts:

1) require scripture (not flexible)

2) disable scripture link when no scripture

3) don't show the toggle when no scripture (i like this, but may take some reworking of our component)

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly or
https://github.com/NewSpring/newspring-app/issues/184
https://github.com/NewSpring/newspring-app/issues/184

**Comment by johnthepink** [comment]
@jbaxleyiii @samclaridge looks like this is becoming more of a thing with new devotionals. we should def handle this before launch

**Comment by johnthepink** [comment]
or... update the devos on the content side, looks like most of them that don't have the scripture listed actually do reference scripture in the content

**Comment by johnthepink** [comment]
we should still handle the case though
