### ISSUE TITLE
Music Player Updates

### ISSUE THREAD

**Issue by samclaridge** [NewSpring/newspring-app#186]
### Current Issues
When playing music on smaller devices the controls aren't fully visible within the viewport. Finding a good solution, while also having track listing beneath the player controls is proving to be problematic. This becomes even more pronounced if we are building towards having the ability to make playlists. If this is something we are planning on doing we may need to pivot back to having separate views for albums and the player, instead of trying to combine them.

Here are some of the ideas I'd been playing with to try and make the artwork and player controls always be visible. The proposed logic behind pulling these off though gets rather convoluted. 

![](https://photos-4.dropbox.com/t/2/AADkGqiJjEnSN0egflpqlW797zk7ysg-JW0PI_BlH9wx5Q/12/5045573/png/32x32/3/1458522000/0/2/Screenshot%202016-03-20%2016.48.29.png/ELe_4wMYkKgEIAEgAigB/b5pj1VXlfv3VeJg6TY-psW2WpHD79rmcrCkqt6B_hVc?size_mode=3&size=1600x1200)

**Comment by jbaxleyiii** [comment]
@samclaridge I think even if they are split we are going to run into issues. Lets say I've got a playlist going (much like a stew) and from the mini player I want to skip ahead three songs. I should be able to click the mini player, have it reveal the full player and the list of tracks.

That being said, I really really like the last two options and since we have the blurred art I would love to use it.

**Comment by samclaridge** [comment]
@jbaxleyiii well if we split it, my thought was there would be an icon that took you to the track listing, much the way iTunes and Spotify do it. This would show the album track listing, or in the event of a custom playlist, the tracks associated with that list. Then the player view would be designed to only ever be the height of the screen with no scrolling.
